# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leavehistory_confirmed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallotment',
            name='leave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_history_table', to='leave.LeaveHistory'),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='endorsement',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Endorsed'), ('2', 'Rejected'), ('3', 'Recommanded')], max_length=20),
        ),
    ]
