# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20161214_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallotment',
            name='leave_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_history_table', to='leave.LeaveHistory'),
        ),
    ]
