# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20161214_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecategory',
            name='leave_type',
            field=models.IntegerField(default=0),
        ),
    ]
