# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_employeeleavesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveallotment',
            name='frequency_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
