# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_leaveallotment_frequency_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavesetting',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
